### ISSUE TITLE
Registration link in email is wrong / not clickable

### ISSUE THREAD

**Issue by kdambekalns** [neos/Neos.IdNeosIo#10] opened 2018-02-07 14:40 UTC
When using https://id.neos.io/user/new to register, the email that is being sent contains an activation link. That link is not clickable, but just text: `/user/activate/...`

**Comment by kdambekalns** [comment] 2018-02-07 14:41
The same is the case for links in password reset mails, has been reported.

**Comment by bwaidelich** [comment] 2018-04-11 13:52
I can confirm.. I assume that the error lies in https://github.com/flownative/flow-doubleoptin/ no?

**Comment by kdambekalns** [comment] 2018-04-17 07:55
I guess it's caused by Flow change. We recently had to do this in a project of ours:

**before**

```
            $currentRequestHandler = $this->bootstrap->getActiveRequestHandler();
            if ($currentRequestHandler instanceof HttpRequestHandlerInterface) {
                $httpRequest = $currentRequestHandler->getHttpRequest();
            } else {
                putenv('FLOW_REWRITEURLS=1');
                $httpRequest = Request::createFromEnvironment();
                $httpRequest->setBaseUri(new Uri($this->baseUriSetting));
            }
            $actionRequest = new ActionRequest($httpRequest);
            $this->doubleOptInHelper->setRequest($actionRequest);
```

**after**

```
        $currentRequestHandler = $this->bootstrap->getActiveRequestHandler();
        if ($currentRequestHandler instanceof HttpRequestHandlerInterface) {
            $httpRequest = $currentRequestHandler->getHttpRequest();
        } else {
            putenv('FLOW_REWRITEURLS=1');
            $baseUri = new Uri($this->baseUriSetting);
            $httpRequest = Request::create($baseUri, 'POST');
        }
        $actionRequest = new ActionRequest($httpRequest);
        $this->doubleOptInHelper->setRequest($actionRequest);
```

**Comment by bwaidelich** [comment] 2018-04-23 14:32
@kdambekalns I assume this has to be fixed in your package, right? (https://github.com/flownative/flow-doubleoptin/issues/10)

**Comment by bwaidelich** [comment] 2018-04-26 08:13
OK, thanks for clarifying. I'll look into this

**Comment by kdambekalns** [comment] 2018-06-27 07:07
@bwaidelich Is this still on your radar? Or should someone else tackle it?

**Comment by bwaidelich** [comment] 2018-06-27 07:22
@kdambekalns Thanks for the ping. I just copied it to a fresh todo list and will tackle it asap! But I unassign myself from the issue for now in case someone else is faster.
Sorry for the cookie licking ;)

**Comment by bwaidelich** [comment] 2018-07-02 16:20
It took me a while to set this all up locally and.. I can't reproduce the issue.
Karstens comments above don't apply because we trigger the `doubleOptInHelper` from action controller using the existing `ActionRequest`.
The only way I can reproduce this locally is by setting an *empty* `baseUri`

**Closed** 2018-07-02 17:04 UTC
Labels: bug
